=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dtd/topaze.dtd
<!ELEMENT dataset (
    bonpreparation*,
    elementlivraison*,
    tracage*)>

<!ELEMENT bonpreparation EMPTY>
<!ATTLIST bonpreparation
    id CDATA #REQUIRED
    causeNonlivraison CDATA #IMPLIED
    dateDebutPreparation CDATA #IMPLIED
    dateInitiation CDATA #IMPLIED
    dateLivraisonTermine CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateRetourTermine CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    idClient CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeBonPreparation CDATA #IMPLIED
>

<!ELEMENT elementlivraison EMPTY>
<!ATTLIST elementlivraison
    id CDATA #REQUIRED
    acteur CDATA #IMPLIED
    addresseLivraison CDATA #IMPLIED
    ancienCodeColis CDATA #IMPLIED
    ancienRetailerPackagerId CDATA #IMPLIED
    causeNonlivraison CDATA #IMPLIED
    codeColis CDATA #IMPLIED
    dateDebutPreparation CDATA #IMPLIED
    dateInitiation CDATA #IMPLIED
    dateLivraisonTermine CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateRetourTermine CDATA #IMPLIED
    numEC CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceAncienProduit CDATA #IMPLIED
    referenceProduit CDATA #IMPLIED
    resiliationPartiel CDATA #IMPLIED
    retailerPackagerId CDATA #IMPLIED
    typeBonPreparation CDATA #IMPLIED
    typeContrat CDATA #IMPLIED
    bonPreparationParent CDATA #IMPLIED
>

<!ELEMENT tracage EMPTY>
<!ATTLIST tracage
    id CDATA #REQUIRED
    date CDATA #IMPLIED
    descr CDATA #IMPLIED
    ip CDATA #IMPLIED
    reference CDATA #IMPLIED
    target CDATA #IMPLIED
    type CDATA #IMPLIED
    user CDATA #IMPLIED
>

=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dataset/test-topaze-bon-migration.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<bonpreparation/>
<bonpreparation id="1" reference="REF_BM_GLOBAL" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="MIGRATION" />
<bonpreparation id="5" reference="REF_BM_GLOBAL_A_PREPARER" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="LIVRAISON"/>
<bonpreparation id="2" reference="REF_BM_GLOBAL_MIGRATION" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="MIGRATION" />


<elementlivraison id="2" reference="REF_EM1" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="SWAP" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="3" reference="REF_EM2" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="SWAP" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="4" reference="REF_EM3" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="SWAP" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="MIGRATION" />

<elementlivraison id="6" reference="REF_BM_A_RETOUR" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" acteur="SWAP" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="7" reference="REF_BM_A_LIVRE" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" acteur="SWAP" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="8" reference="REF_BM_A_PREPARER3" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LIVRAISON" />
</dataset>

=== oussama-denden/tp/livraison/livraison-outil/src/test/resources/dataset/test-topaze-bon-preparation.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Topaze.dtd">
<dataset>
<bonpreparation/>
<bonpreparation id="1" reference="REF_BP_GLOBAL" addressLivraison="ADR_LIV" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="GLOBAL" etatBonPreparation="LIVRAISON" />
<bonpreparation id="2" reference="REF_SBP1" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />
<bonpreparation id="3" reference="REF_SBP2" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />
<bonpreparation id="4" reference="REF_SBP3" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />

<bonpreparation id="5" reference="REF_BP_GLOBAL_A_PREPARER" addressLivraison="ADR_LIV" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="GLOBAL" etatBonPreparation="LIVRAISON" />
<bonpreparation id="6" reference="REF_SBP_A_PREPARER1" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />
<bonpreparation id="7" reference="REF_SBP_A_PREPARER2" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />
<bonpreparation id="8" reference="REF_SBP_A_PREPARER3" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" idClient="ID_CLIENT"  outilLivraison="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />

</dataset>

=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dataset/test-get-element-code-produit.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<bonpreparation/>
<bonpreparation id="1" reference="REF_BP_GLOBAL" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="LIVRAISON" />
<bonpreparation id="5" reference="REF_BP_GLOBAL_A_PREPARER" dateInitiation="[now-7days]" idClient="ID_CLIENT" typeBonPreparation="MIGRATION"/>

<elementlivraison id="2" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]"  dateLivraisonTermine="[now]"  acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="3" reference="REF_SBP2" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraisonTermine="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="4" reference="REF_SBP3" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraisonTermine="[now]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LIVRAISON" />

<elementlivraison id="6" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT_1" dateInitiation="[now-7days]" dateLivraisonTermine="[now+7days]"  acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="7" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraisonTermine="[now]"   acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="8" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="5" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraisonTermine="[now]"   acteur="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LIVRAISON" />
</dataset>

=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dataset/test-get-element-code-colis.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<bonpreparation/>
<bonpreparation id="1" reference="REF_BP_LIVRAISON" dateInitiation="[now-7days]"  idClient="ID_CLIENT" typeBonPreparation="LIVRAISON" />
<bonpreparation id="2" reference="REF_BP__RETOUR" dateInitiation="[now-7days]"  dateLivraisonTermine="[now]" idClient="ID_CLIENT" typeBonPreparation="RETOUR" />
<bonpreparation id="3" reference="REF_BP_LIVRAISON" dateInitiation="[now-7days]" dateLivraisonTermine="[now]"  idClient="ID_CLIENT" typeBonPreparation="MIGRATION"/>

<elementlivraison id="4" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" codeColis="1" dateInitiation="[now-7days]"   dateLivraisonTermine="[now]"  acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="5" reference="REF_SBP2" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" codeColis="2" dateInitiation="[now-7days]"  dateLivraisonTermine="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="6" reference="REF_SBP3" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" codeColis="3" dateInitiation="[now-7days]"  dateLivraisonTermine="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LIVRAISON" />

<elementlivraison id="7" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="3" retailerPackagerId="CODE_PRODUIT_1" codeColis="5" datePreparation="[now]"  dateInitiation="[now-7days]"  dateLivraisonTermine="[now+7days]" dateRetourTermine="[now+7days]"  acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="MIGRATION" />
<elementlivraison id="8" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="3" retailerPackagerId="CODE_PRODUIT" codeColis="6" dateInitiation="[now-7days]" dateLivraisonTermine="[now]"   acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />
<elementlivraison id="9" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="3" retailerPackagerId="CODE_PRODUIT" codeColis="7" dateInitiation="[now-7days]" dateLivraisonTermine="[now]"   acteur="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="LIVRAISON" />



<elementlivraison id="10" reference="REF_SBP1" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" codeColis="1" dateInitiation="[now-7days]"   dateLivraisonTermine="[now]"  dateRetourTermine="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="RETOUR" />
<elementlivraison id="11" reference="REF_SBP2" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" codeColis="2" dateInitiation="[now-7days]"  dateLivraisonTermine="[now]" dateRetourTermine="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="RETOUR" />
<elementlivraison id="12" reference="REF_SBP3" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" codeColis="3" dateInitiation="[now-7days]"  dateLivraisonTermine="[now]" dateRetourTermine="[now]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_TEMPLATE" typeBonPreparation="RETOUR" />

</dataset>

=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dataset/test-initiation-recuperation.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<bonpreparation/>
<bonpreparation id="1" reference="REF_BP_GLOBAL_LIVRER" dateInitiation="[now-7days]" dateLivraisonTermine="[now+7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="LIVRAISON" />
<bonpreparation id="2" reference="REF_BP_GLOBAL_NON_LIVRER" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  typeBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST"/>
<bonpreparation id="3" reference="REF_BP_RETOURNER" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraisonTermine="[now+7days]" idClient="ID_CLIENT"  typeBonPreparation="LIVRAISON" />
<bonpreparation id="4" reference="REF_BP_RETOURNER" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  typeBonPreparation="RETOUR" />

<elementlivraison id="1" reference="REF_SBP1" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraisonTermine="[now+7days]" datePreparation="[now]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="LIVRAISON" typeContrat="LOCATION" />
<elementlivraison id="2" reference="REF_SBP2" bonPreparationParent="1" codeColis="1" dateInitiation="[now-7days]" dateLivraisonTermine="[now+7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="LIVRAISON" typeContrat="VENTE" />
<elementlivraison id="3" reference="REF_SBP3" bonPreparationParent="1" codeColis="1" dateInitiation="[now-7days]" dateLivraisonTermine="[now+7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="LIVRAISON" typeContrat="LOCATION" />

<elementlivraison id="5" reference="REF_SBP3" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST" typeContrat="LOCATION" />
<elementlivraison id="6" reference="REF_SBP4" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST" typeContrat="LOCATION" />

<elementlivraison id="7" reference="REF_SBP5" addresseLivraison="ADR_LIV" bonPreparationParent="3" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraisonTermine="[now+7days]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeContrat="LOCATION" typeBonPreparation="LIVRAISON" />

<elementlivraison id="8" reference="REF_SBP6" addresseLivraison="ADR_LIV" bonPreparationParent="4" retailerPackagerId="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="RETOUR" />

</dataset>

=== oussama-denden/tp/livraison/livraison-outil/src/test/resources/dataset/test-initiation-recuperation.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Topaze.dtd">
<dataset>
<bonpreparation id="1" reference="REF_BP_GLOBAL_LIVRER" addressLivraison="ADR_LIV" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" idClient="ID_CLIENT" typeBonPreparation="GLOBAL" etatBonPreparation="LIVRAISON" />
<bonpreparation id="2" reference="REF_SBP1" bonPreparationParent="1" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" outilLivraison="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="ABONNEMENT" etatBonPreparation="LIVRAISON" />
<bonpreparation id="3" reference="REF_SBP2" bonPreparationParent="1" codeColis="1" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON"/>
<bonpreparation id="4" reference="REF_SBP3" bonPreparationParent="1" codeColis="1" dateInitiation="[now-7days]" dateLivraison="[now+7days]" datePreparation="[now]" outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="VENTE" etatBonPreparation="LIVRAISON"/>

<bonpreparation id="5" reference="REF_BP_GLOBAL_NON_LIVRER" addressLivraison="ADR_LIV" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  typeBonPreparation="GLOBAL" etatBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST"/>
<bonpreparation id="6" reference="REF_SBP3" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST"/>
<bonpreparation id="7" reference="REF_SBP4" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" causeNonlivraison="CAUSE_NON_LIVRAIS_TST"/>

<bonpreparation id="8" reference="REF_BP_RETOURNER" addressLivraison="ADR_LIV" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraison="[now+7days]" idClient="ID_CLIENT"  typeBonPreparation="GLOBAL" etatBonPreparation="LIVRAISON" />
<bonpreparation id="9" reference="REF_SBP5" addressLivraison="ADR_LIV" bonPreparationParent="8" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" dateLivraison="[now+7days]" idClient="ID_CLIENT" outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="LIVRAISON" />

<bonpreparation id="10" reference="re-REF_BP_RETOURNER" addressLivraison="ADR_LIV" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT"  typeBonPreparation="GLOBAL" etatBonPreparation="RECUPERATION" />
<bonpreparation id="11" reference="re-REF_SBP6" addressLivraison="ADR_LIV" bonPreparationParent="10" codeProduit="CODE_PRODUIT" dateInitiation="[now-7days]" datePreparation="[now]" idClient="ID_CLIENT" outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT" typeBonPreparation="LOCATION" etatBonPreparation="RECUPERATION" />
</dataset>

=== oussama-denden/tp/livraison/livraison-core/src/test/resources/dataset/test-recuperation.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset> 
<bonpreparation id="1" reference="REF_BP_GLOBAL_RETOUR" dateInitiation="[now-7days]" idClient="1"  typeBonPreparation="RETOUR"  />
<bonpreparation id="2" reference="REF_BP_GLOBAL_RETOUR_NON_PREPARER" dateInitiation="[now-7days]" idClient="1"  typeBonPreparation="RETOUR" />
<bonpreparation id="3" reference="REF_BP_GLOBAL_RETOUR-PREPARER" dateInitiation="[now-7days]" datePreparation="[now]" idClient="1"  typeBonPreparation="RETOUR"  />
<elementlivraison id="2" reference="REF_SBP_1" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT_1" dateInitiation="[now-7days]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="RETOUR"/>
<elementlivraison id="3" reference="REF_SBP_2" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT_2" dateInitiation="[now-7days]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="RETOUR" codeColis="CODE_COLIS_TST_1"/>
<elementlivraison id="4" reference="REF_SBP_3" addresseLivraison="ADR_LIV" bonPreparationParent="1" retailerPackagerId="CODE_PRODUIT_3" dateInitiation="[now-7days]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="RETOUR" codeColis="CODE_COLIS_TST_1"/>

<elementlivraison id="6" reference="REF_SBP_4" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT_1" dateInitiation="[now-7days]" datePreparation="[now]" acteur="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="RETOUR" />
<elementlivraison id="7" reference="REF_SBP_5" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT_2" dateInitiation="[now-7days]" datePreparation="[now]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="RETOUR" codeColis="CODE_COLIS_TST_1"/>
<elementlivraison id="8" reference="REF_SBP_6" addresseLivraison="ADR_LIV" bonPreparationParent="2" retailerPackagerId="CODE_PRODUIT_3" dateInitiation="[now-7days]" acteur="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="RETOUR" codeColis="CODE_COLIS_TST_1"/>

</dataset>
