=== oussama-denden/tp/topaze-finder/src/test/resources/dtd/topaze.dtd
<!ELEMENT dataset (
    avenant*,
    contrat*,
    contrathistorique*,
    elementcontractuel*,
    elementcontractuelfraiscontrat*,
    elementcontractuelfraiscontrathistorique*,
    elementcontractuelhistorique*,
    fraiscontrat*,
    keygen*,
    modification*,
    politiquecession*,
    politiquemigration*,
    politiquerenouvellement*,
    politiqueresiliation*,
    politiquevalidation*,
    reduction*,
    bonpreparation*,
    elementlivraison*)>

<!ELEMENT avenant EMPTY>
<!ATTLIST avenant
    id CDATA #REQUIRED
    commentaire CDATA #IMPLIED
    commentaireAnnulation CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    dateModification CDATA #IMPLIED
    referenceContrat CDATA #IMPLIED
    typeAvenant CDATA #IMPLIED
    version CDATA #IMPLIED
    politiqueCessionId CDATA #IMPLIED
    politiqueMigrationId CDATA #IMPLIED
    politiqueRenouvellementId CDATA #IMPLIED
>

<!ELEMENT contrat EMPTY>
<!ATTLIST contrat
    id CDATA #REQUIRED
    dateDebutFacturation CDATA #IMPLIED
    dateDerniereFacture CDATA #IMPLIED
    dateFactureResiliation CDATA #IMPLIED
    dateFinContrat CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateValidation CDATA #IMPLIED
    idClient CDATA #IMPLIED
    reference CDATA #IMPLIED
    segmentTVA CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeResiliation CDATA #IMPLIED
    politiqueResiliationId CDATA #IMPLIED
    politiqueValidationId CDATA #IMPLIED
>

<!ELEMENT contrathistorique EMPTY>
<!ATTLIST contrathistorique
    id CDATA #REQUIRED
    dateDebutFacturation CDATA #IMPLIED
    dateDerniereFacture CDATA #IMPLIED
    dateFactureResiliation CDATA #IMPLIED
    dateFinContrat CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateValidation CDATA #IMPLIED
    idClient CDATA #IMPLIED
    reference CDATA #IMPLIED
    segmentTVA CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeResiliation CDATA #IMPLIED
    version CDATA #IMPLIED
    politiqueResiliationId CDATA #IMPLIED
    politiqueValidationId CDATA #IMPLIED
>

<!ELEMENT elementcontractuel EMPTY>
<!ATTLIST elementcontractuel
    id CDATA #REQUIRED
    dateDebutFacturation CDATA #IMPLIED
    dateDerniereFacture CDATA #IMPLIED
    dateFactureResiliation CDATA #IMPLIED
    dateFinContrat CDATA #IMPLIED
    dateFinDuree CDATA #IMPLIED
    dateFinEngagement CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateValidation CDATA #IMPLIED
    duree CDATA #IMPLIED
    engagement CDATA #IMPLIED
    idAdrFacturation CDATA #IMPLIED
    idAdrLivraison CDATA #IMPLIED
    isMigre CDATA #IMPLIED
    modeFacturation CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    numEC CDATA #IMPLIED
    numeroCommande CDATA #IMPLIED
    periodicite CDATA #IMPLIED
    referenceModePaiement CDATA #IMPLIED
    referenceProduit CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    remboursable CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    typeResiliation CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
    contratParent CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    politiqueResiliationId CDATA #IMPLIED
>

<!ELEMENT elementcontractuelfraiscontrat EMPTY>
<!ATTLIST elementcontractuelfraiscontrat
    elementcontractuel_id CDATA #REQUIRED
    frais_id CDATA #REQUIRED
>

<!ELEMENT elementcontractuelfraiscontrathistorique EMPTY>
<!ATTLIST elementcontractuelfraiscontrathistorique
    elementcontractuelhistorique_id CDATA #REQUIRED
    frais_id CDATA #REQUIRED
>

<!ELEMENT elementcontractuelhistorique EMPTY>
<!ATTLIST elementcontractuelhistorique
    id CDATA #REQUIRED
    dateDebutFacturation CDATA #IMPLIED
    dateDerniereFacture CDATA #IMPLIED
    dateFactureResiliation CDATA #IMPLIED
    dateFinContrat CDATA #IMPLIED
    dateFinDuree CDATA #IMPLIED
    dateFinEngagement CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateValidation CDATA #IMPLIED
    duree CDATA #IMPLIED
    engagement CDATA #IMPLIED
    idAdrFacturation CDATA #IMPLIED
    idAdrLivraison CDATA #IMPLIED
    isMigre CDATA #REQUIRED
    modeFacturation CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    numEC CDATA #IMPLIED
    numeroCommande CDATA #IMPLIED
    periodicite CDATA #IMPLIED
    referenceModePaiement CDATA #IMPLIED
    referenceProduit CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    remboursable CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    typeResiliation CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
    contratParent CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    politiqueResiliationId CDATA #IMPLIED
>

<!ELEMENT fraiscontrat EMPTY>
<!ATTLIST fraiscontrat
    id CDATA #REQUIRED
    montant CDATA #IMPLIED
    nombreMois CDATA #IMPLIED
    ordre CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeFrais CDATA #IMPLIED
>

<!ELEMENT keygen EMPTY>
<!ATTLIST keygen
    id CDATA #REQUIRED
    entite CDATA #IMPLIED
    reference CDATA #IMPLIED
>

<!ELEMENT modification EMPTY>
<!ATTLIST modification
    id CDATA #REQUIRED
    numEC CDATA #IMPLIED
    trameJson CDATA #IMPLIED
    avenantId CDATA #IMPLIED
>

<!ELEMENT politiquecession EMPTY>
<!ATTLIST politiquecession
    id CDATA #REQUIRED
    conserverAncienneReduction CDATA #IMPLIED
    dateAction CDATA #IMPLIED
    fraisCession CDATA #REQUIRED
    montantRemboursement CDATA #IMPLIED
    remboursement CDATA #REQUIRED
>

<!ELEMENT politiquemigration EMPTY>
<!ATTLIST politiquemigration
    id CDATA #REQUIRED
    dateAction CDATA #IMPLIED
    fraisCreation CDATA #REQUIRED
    fraisMigration CDATA #IMPLIED
    fraisResiliation CDATA #REQUIRED
    montantRemboursement CDATA #IMPLIED
    montantResiliation CDATA #IMPLIED
    penalite CDATA #REQUIRED
    reductionAncienne CDATA #REQUIRED
    remboursement CDATA #REQUIRED
    user CDATA #IMPLIED
>

<!ELEMENT politiquerenouvellement EMPTY>
<!ATTLIST politiquerenouvellement
    id CDATA #REQUIRED
    conserverAncienneReduction CDATA #IMPLIED
    forceRenouvellement CDATA #IMPLIED
    user CDATA #IMPLIED
>

<!ELEMENT politiqueresiliation EMPTY>
<!ATTLIST politiqueresiliation
    id CDATA #REQUIRED
    commentaire CDATA #IMPLIED
    commentaireAnnulation CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    dateRemboursement CDATA #IMPLIED
    dateResiliation CDATA #IMPLIED
    delaiDeSecurite CDATA #IMPLIED
    enCascade CDATA #REQUIRED
    fraisResiliation CDATA #REQUIRED
    montantRemboursement CDATA #IMPLIED
    montantResiliation CDATA #IMPLIED
    motif CDATA #IMPLIED
    penalite CDATA #REQUIRED
    remboursement CDATA #REQUIRED
    typeResiliation CDATA #IMPLIED
>

<!ELEMENT politiquevalidation EMPTY>
<!ATTLIST politiquevalidation
    id CDATA #REQUIRED
    checkIsPackagerCreationPossible CDATA #IMPLIED
    commentaire CDATA #IMPLIED
    fraisCreation CDATA #IMPLIED
>

<!ELEMENT reduction EMPTY>
<!ATTLIST reduction
    id CDATA #REQUIRED
    codeCatalogueReduction CDATA #IMPLIED
    contextReduction CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    dateDebut CDATA #IMPLIED
    dateFin CDATA #IMPLIED
    isAffichableSurFacture CDATA #IMPLIED
    nbUtilisationEnCours CDATA #IMPLIED
    nbUtilisationMax CDATA #IMPLIED
    numEC CDATA #IMPLIED
    ordre CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceContrat CDATA #IMPLIED
    titre CDATA #IMPLIED
    typeFrais CDATA #IMPLIED
    typeReduction CDATA #IMPLIED
    typeValeur CDATA #IMPLIED
    valeur CDATA #IMPLIED
    version CDATA #IMPLIED
>

<!ELEMENT bonpreparation EMPTY>
<!ATTLIST bonpreparation
    id CDATA #REQUIRED
    causeNonlivraison CDATA #IMPLIED
    dateDebutPreparation CDATA #IMPLIED
    dateInitiation CDATA #IMPLIED
    dateLivraisonTermine CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateRetourTermine CDATA #IMPLIED
    idClient CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeBonPreparation CDATA #IMPLIED
>

<!ELEMENT elementlivraison EMPTY>
<!ATTLIST elementlivraison
    id CDATA #REQUIRED
    acteur CDATA #IMPLIED
    addresseLivraison CDATA #IMPLIED
    ancienCodeColis CDATA #IMPLIED
    ancienRetailerPackagerId CDATA #IMPLIED
    causeNonlivraison CDATA #IMPLIED
    codeColis CDATA #IMPLIED
    dateDebutPreparation CDATA #IMPLIED
    dateInitiation CDATA #IMPLIED
    dateLivraisonTermine CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateRetourTermine CDATA #IMPLIED
    numEC CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceAncienProduit CDATA #IMPLIED
    referenceProduit CDATA #IMPLIED
    resiliationPartiel CDATA #IMPLIED
    retailerPackagerId CDATA #IMPLIED
    typeBonPreparation CDATA #IMPLIED
    typeContrat CDATA #IMPLIED
    bonPreparationParent CDATA #IMPLIED
>

=== oussama-denden/tp/topaze-finder/src/test/resources/dataset/findContratTest.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<contrat/>
<contrat id="10000" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<contrat id="10001" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<contrat id="10002" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<contrat id="10003" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<contrat id="10004" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<contrat id="10005" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>

<elementcontractuel/>
<elementcontractuel id="10000" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10000" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<elementcontractuel id="10001" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10001" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<elementcontractuel id="10002" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10002" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<elementcontractuel id="10003" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10003" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<elementcontractuel id="10004" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10004" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<elementcontractuel id="10005" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10005" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />

</dataset>

=== oussama-denden/tp/contrat/contrat-core/src/test/resources/dataset/valider-contrat.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>

<contrat id="1" reference="REF_GB" titre="Contrat Pour Test" datePreparation="[now]"  />

<elementcontractuel id="2" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="PREMIER_MOIS"    referenceProduit="PROD-01" titre="Contrat ABONNEMENT" numEC="1" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>
<elementcontractuel id="3" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="DATE_ANNIVERSAIRE"  referenceProduit="PROD-02" titre="Contrat LOCATION" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0002" montant="12" typeTVA="S"/>
<elementcontractuel id="4" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="PREMIER_MOIS"  referenceProduit="PROD-03" titre="Contrat VENTE" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0003" montant="12" typeTVA="S"/>
<elementcontractuel id="5" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="DATE_ANNIVERSAIRE"  referenceProduit="PROD-01" titre="Contrat VENTE" numEC="2" datePreparation="[now]" contratParent="1" referenceModePaiement="rum-0004" montant="12" typeTVA="S"/>

<fraiscontrat id="1" titre="Frais de dossier" montant="20" typeFrais="CREATION"/>

<elementcontractuelfraiscontrat elementcontractuel_id="2" frais_id="1"/>

</dataset>

=== oussama-denden/tp/topaze-finder/src/test/resources/dataset/getRPIDTest.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>

<contrat/>
<contrat id="10000" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>

<elementcontractuel/>
<elementcontractuel id="10000" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10000" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />

<bonpreparation/>
<bonpreparation id="10000" reference="00010000" dateInitiation="[now-7days]" idClient="ID_CLIENT" typeBonPreparation="LIVRAISON"/>

<elementlivraison/>
<elementlivraison id="10000" numEC="1" reference="00010000-1" bonPreparationParent="10000" addresseLivraison="ADR_LIV" retailerPackagerId="RPID" dateInitiation="[now-7days]" datePreparation="[now]"  dateLivraisonTermine="[now]"  acteur="PACKAGER" referenceProduit="REF_PRODUIT" typeBonPreparation="LIVRAISON" />

</dataset>

=== oussama-denden/tp/contrat/contrat-core/src/test/resources/dataset/ajouter-reduction.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>

<contrat id="1" reference="REF_GB" titre="Contrat Pour Test" datePreparation="[now]"  />
<contrat id="2" reference="REF_GB2" titre="Contrat Pour Test" datePreparation="[now]" />

<elementcontractuel id="2" numeroCommande="1" modePaiement="CHEQUE" periodicite="2" modeFacturation="PREMIER_MOIS"    referenceProduit="PROD-01" typeProduit="SERVICE" titre="Contrat ABONNEMENT" numEC="1" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>
<elementcontractuel id="3" numeroCommande="1" modePaiement="CHEQUE" periodicite="3" modeFacturation="DATE_ANNIVERSAIRE"  referenceProduit="PROD-02" typeProduit="BIEN" titre="Contrat LOCATION" numEC="2" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0002" montant="12" typeTVA="S"/>
<elementcontractuel id="4" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="PREMIER_MOIS"  referenceProduit="PROD-03" titre="Contrat VENTE" typeProduit="BIEN" numEC="3"  datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0003" montant="12" typeTVA="S"/>
<elementcontractuel id="5" numeroCommande="1" modePaiement="CHEQUE" modeFacturation="DATE_ANNIVERSAIRE"  referenceProduit="PROD-01" titre="Contrat VENTE" typeProduit="BIEN" numEC="4" datePreparation="[now]" contratParent="1" referenceModePaiement="rum-0004" montant="12" typeTVA="S"/>
<elementcontractuel id="6" numeroCommande="1" modePaiement="CHEQUE" periodicite="1" modeFacturation="PREMIER_MOIS"    referenceProduit="PROD-01" titre="Contrat ABONNEMENT" typeProduit="BIEN" numEC="5" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="2" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>

<fraiscontrat id="1" titre="Frais de dossier" montant="20" typeFrais="CREATION" />

<elementcontractuelfraiscontrat elementcontractuel_id="2" frais_id="1"/>



<reduction id="1" contextReduction="GLOBAL" numEC="5" referenceContrat="REF_GB2" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" />
</dataset>

=== oussama-denden/tp/contrat/contrat-core/src/test/resources/dataset/reductions-valide.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>

<contrat id="1" reference="REF_CONTRAT" titre="Contrat Pour Test" datePreparation="[now]"  />

<elementcontractuel id="2" numEC="1" numeroCommande="1" modePaiement="CHEQUE" periodicite="2" modeFacturation="PREMIER_MOIS" referenceProduit="PROD-01" typeProduit="SERVICE" titre="Contrat ABONNEMENT" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>

<reduction id="1" contextReduction="GLOBAL" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" dateAnnulation="[now]"/>
<reduction id="2" contextReduction="GLOBAL" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" />
<reduction id="3" contextReduction="GLOBAL" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" codeCatalogueReduction="ref-catalogue"/>
<reduction id="4" contextReduction="PARTIEL" numEC="1" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" nbUtilisationEnCours="3" nbUtilisationMax="3"/>
<reduction id="5" contextReduction="PARTIEL" numEC="1" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" dateDebut="[now-10months]" dateFin="[now-10days]"/>
<reduction id="6" contextReduction="PARTIEL" numEC="1" referenceContrat="REF_CONTRAT" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" isAffichableSurFacture="false" codeCatalogueReduction="ref-catalogue"/>

</dataset>

=== oussama-denden/tp/contrat/contrat-core/src/test/resources/dataset/Annuler-reduction.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>

<contrat id="1" reference="REF_GB" titre="Contrat Pour Test" datePreparation="[now]"  />

<elementcontractuel id="1" numeroCommande="1" modePaiement="CHEQUE" periodicite="1" modeFacturation="PREMIER_MOIS"    referenceProduit="PROD-01" titre="Contrat ABONNEMENT" numEC="1" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>
<elementcontractuel id="2" numeroCommande="1" modePaiement="CHEQUE" periodicite="1" modeFacturation="PREMIER_MOIS"   referenceProduit="PROD-02" titre="Contrat ABONNEMENT" numEC="2" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="rum-0001" montant="22" typeTVA="S"/>

<reduction id="1" contextReduction="GLOBAL" referenceContrat="REF_GB" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" nbUtilisationEnCours="0" nbUtilisationMax="2" isAffichableSurFacture="false" reference="REF_RED-1"  />
<reduction id="2" contextReduction="GLOBAL"  referenceContrat="REF_GB" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" nbUtilisationEnCours="0" nbUtilisationMax="2" isAffichableSurFacture="false" codeCatalogueReduction="ref-reduc" reference="REF_RED-2" />
 
<reduction id="3" contextReduction="GLOBAL" numEC="1" referenceContrat="REF_GB" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" nbUtilisationEnCours="0" nbUtilisationMax="2" isAffichableSurFacture="false"  reference="REF_RED-3" />
<reduction id="4" contextReduction="GLOBAL" numEC="2" referenceContrat="REF_GB" typeValeur="MOIS" valeur="2" typeReduction="CONTRAT" nbUtilisationEnCours="0" nbUtilisationMax="2" isAffichableSurFacture="false" codeCatalogueReduction="ref-reduc" reference="REF_RED-4" />

</dataset>

=== oussama-denden/tp/contrat/contrat-core/src/test/resources/dataset/ceder-contrat-futur.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<avenant id="1" dateModification="[now]" typeAvenant="CESSION" referenceContrat="REF_GB" politiqueCessionId="1"/>

<contrat id="1" politiqueValidationId="1000" reference="REF_GB" idClient="idCL" titre="Contrat Pour Test" datePreparation="[now]" dateValidation="[now]"  />

<elementcontractuel id="1" numeroCommande="1" modePaiement="CB" periodicite="2" modeFacturation="PREMIER_MOIS" idAdrFacturation="adrFact" idAdrLivraison="adrLiv"  referenceProduit="PROD-01" titre="Contrat ABONNEMENT" numEC="1" datePreparation="[now]" dateDebutFacturation="[now]" contratParent="1" referenceModePaiement="RUM" montant="22" typeTVA="S"/>

<fraiscontrat id="1" titre="Frais de dossier" montant="20" typeFrais="CREATION" contratId="1"/>

<modification id="1" avenantId="1" trameJson="[cession-json-contrat]" />
<modification id="2" avenantId="1" numEC="1" trameJson="[cession-json-element]"/>

<politiquecession id="1" dateAction="[now]" fraisCession="10" montantRemboursement="10" remboursement="1"  conserverAncienneReduction="1"/>

<politiquevalidation id="1000" fraisCreation="false" />

</dataset>

=== oussama-denden/tp/topaze-finder/src/test/resources/dataset/getWelcomeContratInfoTest.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<politiqueresiliation/>
<politiqueresiliation id="10000" fraisResiliation="true" typeResiliation="RIC" remboursement="true" penalite="true" dateResiliation="[now+10days]" enCascade="true" commentaire="commentaire" />
<contrat/>
<contrat id="10000" titre="Contrat Tedst" reference="00010000" idClient="10000"   datePreparation="[now]" dateValidation="[now]" dateDebutFacturation="[now]" politiqueResiliationId="10000"/>
<elementcontractuel/>
<elementcontractuel id="10000" numeroCommande="00010000" numEC="1" modeFacturation="DATE_ANNIVERSAIRE"  idAdrFacturation="id-fact" typeProduit="SERVICE" referenceProduit="avfwpro-confort-s" titre="Contrat ABONNEMENT pour le produit : avfwpro-confort-s" datePreparation="[now]" dateValidation="[now]"  dateDebutFacturation="[now]" contratParent="10000" montant="5" modePaiement="CB" typeTVA="R" periodicite="1" duree="24" engagement="12" dateDerniereFacture="[now+7days]" dateFinContrat="[now+10years]"  />
<fraiscontrat/>
<fraiscontrat id="10000" titre="Frais de dossier" montant="20" typeFrais="RESILIATION" contratId="10000"/>
<avenant/>


</dataset>
