=== oussama-denden/tp/topaze-communication/src/test/resources/dtd/Topaze.dtd
<!ELEMENT dataset (dbmaintain_scripts*,produit*,fraisproduit*,prix*,contrat*,fraiscontrat*,tarif*,bonpreparation*)>

<!ELEMENT dbmaintain_scripts EMPTY>
<!ATTLIST dbmaintain_scripts
    succeeded CDATA #IMPLIED
    file_last_modified_at CDATA #IMPLIED
    executed_at CDATA #IMPLIED
    checksum CDATA #IMPLIED
    file_name CDATA #IMPLIED
	version CDATA #IMPLIED  
>

<!ELEMENT fraisproduit EMPTY>
<!ATTLIST fraisproduit
    id CDATA #IMPLIED
    montant CDATA #IMPLIED
    produitId CDATA #IMPLIED
>

<!ELEMENT prix EMPTY>
<!ATTLIST prix
    id CDATA #IMPLIED
    engagement CDATA #IMPLIED
    montant CDATA #IMPLIED
    typePrix CDATA #IMPLIED
    produitId CDATA #IMPLIED
>

<!ELEMENT produit EMPTY>
<!ATTLIST produit
    id CDATA #IMPLIED
    label CDATA #IMPLIED
    outilsLivraison CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
     xmlTemplatePath CDATA #IMPLIED
    xsdTemplatePath CDATA #IMPLIED
    delaisPreparation CDATA #IMPLIED
>

<!ELEMENT contrat EMPTY>
<!ATTLIST contrat
    id CDATA #IMPLIED
    idAdrFacturation CDATA #IMPLIED
    idAdrLivraison CDATA #IMPLIED
    dateDebutFacturation CDATA #IMPLIED
    dateValidation CDATA #IMPLIED
    engagement CDATA #IMPLIED  
    idClient CDATA #IMPLIED  
    modeFacturation CDATA #IMPLIED  
    reference CDATA #IMPLIED  
    referenceProduit CDATA #IMPLIED  
    titre CDATA #IMPLIED  
    typeContrat CDATA #IMPLIED  
    contratParent CDATA #IMPLIED  
>

<!ELEMENT fraiscontrat EMPTY>
<!ATTLIST fraiscontrat
    id CDATA #IMPLIED
    montant CDATA #IMPLIED
    contratId CDATA #IMPLIED
>

<!ELEMENT tarif EMPTY>
<!ATTLIST tarif
    id CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    referenceModePaiement CDATA #IMPLIED
    typePrix CDATA #IMPLIED
    contratId CDATA #IMPLIED  
>

<!ELEMENT bonpreparation EMPTY>
<!ATTLIST bonpreparation
    id CDATA #IMPLIED
    reference CDATA #IMPLIED  
    idClient CDATA #IMPLIED
    addressLivraison CDATA #IMPLIED
    referenceProduit CDATA #IMPLIED
    codeProduit CDATA #IMPLIED
    codeColis CDATA #IMPLIED
    outilLivraison CDATA #IMPLIED 
    dateInitiation CDATA #IMPLIED
    datePreparation CDATA #IMPLIED
    dateLivraison CDATA #IMPLIED  
    dateRecuperation CDATA #IMPLIED
    etatBonPreparation CDATA #IMPLIED
    typeBonPreparation CDATA #IMPLIED   
    bonPreparationParent CDATA #IMPLIED  
    causeNonlivraison CDATA #IMPLIED
>

=== oussama-denden/tp/catalogue/src/test/resources/dataset/test-topaze-catalogue-add-produit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/topaze.dtd">
<dataset>
<produit id="1" label="PRODUIT_TST" outilsLivraison="PACKAGER" reference="REF_PRODUIT_S_REC"  typeProduit="SERVICE" typeTVA="S"  />
<produit id="2" label="PRODUIT_TST" outilsLivraison="NETDELIVERY" reference="REF_PRODUIT_S_OC"  typeProduit="SERVICE" typeTVA="S" />
<produit id="3" label="PRODUIT_TST" outilsLivraison="NETDELIVERY" reference="REF_PRODUIT_S_TFSF"  typeProduit="SERVICE" typeTVA="S" />
<produit id="4" label="PRODUIT_TST" outilsLivraison="NETDELIVERY" reference="REF_PRODUIT_B_REC"  typeProduit="BIEN" typeTVA="S" />
<produit id="5" label="PRODUIT_TST" outilsLivraison="NETDELIVERY" reference="REF_PRODUIT_B_OS"  typeProduit="BIEN" typeTVA="S" />
<produit id="6" label="PRODUIT_TST" outilsLivraison="PACKAGER" reference="REF_PRODUIT_B_TFSF"  typeProduit="SERVICE" typeTVA="S" />
<produit id="7" label="PRODUIT_TST" outilsLivraison="PACKAGER" reference="REF_PRODUIT_TEMPLATE"  typeProduit="SERVICE" typeTVA="S" xmlTemplatePath="test" xsdTemplatePath="test" />
<produit id="8" label="PRODUIT_TST" outilsLivraison="PACKAGER" reference="REF_PRODUIT_TEMPLATE_N"  typeProduit="SERVICE" typeTVA="S" xmlTemplatePath="testXML" xsdTemplatePath="testXSD" />
<fraisproduit id="1" montant="1000" produitId="1"/>
<prix id="1" engagement="3" montant="1000" typePrix="ONE_SHOT" produitId="1"/>
</dataset>

=== oussama-denden/tp/topaze-communication/src/test/resources/dataset/test-recuperation.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Topaze.dtd">
<dataset>
<bonpreparation id="1" reference="REF_BP_GLOBAL_RETOUR" addressLivraison="ADR_LIV" dateInitiation="[now-7days]" idClient="1"  typeBonPreparation="GLOBAL" etatBonPreparation="RECUPERATION"  />
<bonpreparation id="2" reference="REF_SBP_1" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT_1" dateInitiation="[now-7days]" idClient="1"  outilLivraison="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="ABONNEMENT" etatBonPreparation="RECUPERATION" />
<bonpreparation id="3" reference="REF_SBP_2" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT_2" dateInitiation="[now-7days]" idClient="1"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="LOCATION" etatBonPreparation="RECUPERATION"  codeColis="CODE_COLIS_TST_1"/>
<bonpreparation id="4" reference="REF_SBP_3" addressLivraison="ADR_LIV" bonPreparationParent="1" codeProduit="CODE_PRODUIT_3" dateInitiation="[now-7days]" idClient="1"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="LOCATION" etatBonPreparation="RECUPERATION"  codeColis="CODE_COLIS_TST_1"/>

<bonpreparation id="5" reference="REF_BP_GLOBAL_RETOUR_NON_PREPARER" addressLivraison="ADR_LIV" dateInitiation="[now-7days]" idClient="1"  typeBonPreparation="GLOBAL" etatBonPreparation="RECUPERATION"  />
<bonpreparation id="6" reference="REF_SBP_4" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT_1" dateInitiation="[now-7days]" datePreparation="[now]" idClient="1"  outilLivraison="PACKAGER" referenceProduit="REF_PRODUIT_1" typeBonPreparation="ABONNEMENT" etatBonPreparation="RECUPERATION" />
<bonpreparation id="7" reference="REF_SBP_5" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT_2" dateInitiation="[now-7days]" datePreparation="[now]" idClient="1"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_2" typeBonPreparation="LOCATION" etatBonPreparation="RECUPERATION"  codeColis="CODE_COLIS_TST_1"/>
<bonpreparation id="8" reference="REF_SBP_6" addressLivraison="ADR_LIV" bonPreparationParent="5" codeProduit="CODE_PRODUIT_3" dateInitiation="[now-7days]" idClient="1"  outilLivraison="NETDELIVERY" referenceProduit="REF_PRODUIT_3" typeBonPreparation="LOCATION" etatBonPreparation="RECUPERATION"  codeColis="CODE_COLIS_TST_1"/>
</dataset>
